USE [master]
GO

CREATE DATABASE [LJCData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LJCData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\LJCData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LJCData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016\MSSQL\DATA\LJCData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [LJCData] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LJCData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LJCData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LJCData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LJCData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LJCData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LJCData] SET ARITHABORT OFF 
GO

ALTER DATABASE [LJCData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LJCData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LJCData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LJCData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LJCData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LJCData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LJCData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LJCData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LJCData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LJCData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LJCData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LJCData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LJCData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LJCData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LJCData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LJCData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LJCData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LJCData] SET RECOVERY SIMPLE
GO

ALTER DATABASE [LJCData] SET  MULTI_USER 
GO

ALTER DATABASE [LJCData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LJCData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LJCData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LJCData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LJCData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LJCData] SET QUERY_STORE = OFF
GO

USE [LJCData]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [LJCData] SET  READ_WRITE 
GO


