<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LJCDataAccess5">
      <HintPath>..\External\LJCDataAccess5.dll</HintPath>
    </Reference>
    <Reference Include="LJCDataAccessConfig5">
      <HintPath>..\External\LJCDataAccessConfig5.dll</HintPath>
    </Reference>
    <Reference Include="LJCNetCommon5">
      <HintPath>..\External\LJCNetCommon5.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
