<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LJCControls5\LJCControls5.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LJCNetCommon5">
      <HintPath>..\External\LJCNetCommon5.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>